-- migrate:up
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ship_component_class') THEN
    CREATE TYPE ship_component_class AS ENUM (
      'CIVILIAN',
      'COMPETITION',
      'INDUSTRIAL',
      'MILITARY',
      'STEALTH'
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ship_component_grade') THEN
    CREATE TYPE ship_component_grade AS ENUM (
      'A',
      'B',
      'C',
      'D'
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ship_component_size') THEN
    CREATE TYPE ship_component_size AS ENUM (
      'S0',
      'S1',
      'S2',
      'S3',
      'S4'
    );
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'ship_component_type') THEN
    CREATE TYPE ship_component_type AS ENUM (
      'COOLER',
      'POWER_PLANT',
      'QUANTUM_DRIVE',
      'SHIELD'
    );
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS ship_components (
  id ulid NOT NULL DEFAULT gen_ulid() PRIMARY KEY NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  deleted_at timestamp with time zone,
  name text NOT NULL,
  type ship_component_type NOT NULL,
  size ship_component_size NOT NULL,
  class ship_component_class NOT NULL,
  grade ship_component_grade NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_ship_components_name ON ship_components USING btree (name);

COMMENT ON TABLE ship_components IS E'@omit create,update,delete';

INSERT INTO ship_components (name, type, size, class, grade)
VALUES 
('5CA ''Akura''','SHIELD','S3','CIVILIAN','C'),
('5MA ''Chimalli''','SHIELD','S2','CIVILIAN','C'),
('5SA ''Rhada''','SHIELD','S1','CIVILIAN','C'),
('6CA ''Bila''','SHIELD','S3','CIVILIAN','B'),
('6MA ''Kozane''','SHIELD','S2','CIVILIAN','B'),
('6SA ''Arbiter''','SHIELD','S1','CIVILIAN','B'),
('7CA ''Nargun''','SHIELD','S3','CIVILIAN','A'),
('7MA ''Lorica''','SHIELD','S2','CIVILIAN','A'),
('7SA ''Concord''','SHIELD','S1','CIVILIAN','A'),
('AbsoluteZero','COOLER','S2','COMPETITION','B'),
('Agni','QUANTUM_DRIVE','S3','INDUSTRIAL','B'),
('Aither','QUANTUM_DRIVE','S2','CIVILIAN','B'),
('AllStop','SHIELD','S1','MILITARY','C'),
('Arctic','COOLER','S2','MILITARY','C'),
('ArcticStorm','COOLER','S1','CIVILIAN','C'),
('Armada','SHIELD','S2','INDUSTRIAL','D'),
('ARMOR','SHIELD','S3','CIVILIAN','B'),
('Aspis','SHIELD','S2','INDUSTRIAL','C'),
('Atlas','QUANTUM_DRIVE','S1','CIVILIAN','A'),
('Aufeis','COOLER','S2','CIVILIAN','A'),
('Avalanche','COOLER','S2','MILITARY','A'),
('Balandin','QUANTUM_DRIVE','S3','MILITARY','B'),
('Bamoty','SHIELD','S2','COMPETITION','D'),
('Barbican','SHIELD','S3','INDUSTRIAL','B'),
('Beacon','QUANTUM_DRIVE','S1','MILITARY','C'),
('Berian','COOLER','S1','CIVILIAN','C'),
('BlastChill','COOLER','S1','CIVILIAN','D'),
('Blizzard','COOLER','S3','MILITARY','A'),
('BLOC','SHIELD','S2','CIVILIAN','B'),
('Bolide','POWER_PLANT','S2','MILITARY','B'),
('Bolon','QUANTUM_DRIVE','S2','INDUSTRIAL','C'),
('Bolt','QUANTUM_DRIVE','S2','STEALTH','B'),
('Boreal','COOLER','S2','MILITARY','D'),
('Bracer','COOLER','S1','MILITARY','C'),
('Breton','POWER_PLANT','S1','INDUSTRIAL','A'),
('Bulwark','SHIELD','S1','INDUSTRIAL','C'),
('Burst','QUANTUM_DRIVE','S1','CIVILIAN','B'),
('Cascade','QUANTUM_DRIVE','S2','CIVILIAN','D'),
('Castra','SHIELD','S0','INDUSTRIAL','C'),
('Celestial','POWER_PLANT','S3','CIVILIAN','B'),
('Centurion','POWER_PLANT','S3','MILITARY','C'),
('Charger','POWER_PLANT','S1','MILITARY','D'),
('Chill-Max','COOLER','S3','INDUSTRIAL','A'),
('Cirrus','POWER_PLANT','S2','STEALTH','C'),
('Citadel','SHIELD','S2','INDUSTRIAL','B'),
('Cloak','SHIELD','S1','STEALTH','D'),
('ColdSnap','COOLER','S2','CIVILIAN','C'),
('ColdSurge','COOLER','S3','CIVILIAN','D'),
('Colossus','QUANTUM_DRIVE','S1','INDUSTRIAL','B'),
('CoolCore','COOLER','S2','INDUSTRIAL','C'),
('CoverAll','SHIELD','S2','MILITARY','B'),
('Crossfield','QUANTUM_DRIVE','S2','MILITARY','C'),
('Cryo-Star','COOLER','S1','CIVILIAN','B'),
('Cryo-Star EX','COOLER','S2','CIVILIAN','B'),
('Cryo-Star SL','COOLER','S0','CIVILIAN','B'),
('Cryo-Star XL','COOLER','S3','CIVILIAN','B'),
('DayBreak','POWER_PLANT','S2','CIVILIAN','C'),
('Defiant','POWER_PLANT','S0','INDUSTRIAL','B'),
('DeltaMax','POWER_PLANT','S1','STEALTH','B'),
('Diligence','POWER_PLANT','S2','INDUSTRIAL','C'),
('Drassik','POWER_PLANT','S3','MILITARY','D'),
('Draug','COOLER','S3','CIVILIAN','A'),
('Drift','QUANTUM_DRIVE','S1','STEALTH','C'),
('Drifter','QUANTUM_DRIVE','S3','CIVILIAN','D'),
('DuraJet','POWER_PLANT','S0','CIVILIAN','D'),
('Durango','POWER_PLANT','S3','INDUSTRIAL','A'),
('DynaFlux','POWER_PLANT','S1','MILITARY','B'),
('Echo','QUANTUM_DRIVE','S3','CIVILIAN','D'),
('Eclipse','POWER_PLANT','S2','STEALTH','A'),
('Eco-Flow','COOLER','S1','INDUSTRIAL','B'),
('Elsen','COOLER','S3','CIVILIAN','A'),
('Endo','COOLER','S1','CIVILIAN','B'),
('Endurance','POWER_PLANT','S1','INDUSTRIAL','B'),
('Eos','QUANTUM_DRIVE','S1','CIVILIAN','C'),
('Erebos','QUANTUM_DRIVE','S3','CIVILIAN','A'),
('ExoGen','POWER_PLANT','S2','MILITARY','D'),
('Expedition','QUANTUM_DRIVE','S1','CIVILIAN','C'),
('Falco','SHIELD','S1','COMPETITION','D'),
('Fierell Cascade','POWER_PLANT','S1','MILITARY','B'),
('Fissure','QUANTUM_DRIVE','S3','CIVILIAN','C'),
('Flash','QUANTUM_DRIVE','S2','CIVILIAN','B'),
('FlashFreeze','COOLER','S1','CIVILIAN','B'),
('Flood','QUANTUM_DRIVE','S1','CIVILIAN','D'),
('ForceWall','SHIELD','S1','MILITARY','B'),
('Fortitude','POWER_PLANT','S1','INDUSTRIAL','C'),
('FoxFire','QUANTUM_DRIVE','S1','COMPETITION','B'),
('FR-66','SHIELD','S1','MILITARY','A'),
('FR-76','SHIELD','S2','MILITARY','A'),
('FR-86','SHIELD','S3','MILITARY','A'),
('Fridan','COOLER','S0','CIVILIAN','C'),
('Frost-Star','COOLER','S1','CIVILIAN','C'),
('Frost-Star EX','COOLER','S2','CIVILIAN','C'),
('Frost-Star SL','COOLER','S0','CIVILIAN','C'),
('Frost-Star XL','COOLER','S3','CIVILIAN','C'),
('FrostBite','COOLER','S3','CIVILIAN','B'),
('FrostBurn','COOLER','S3','CIVILIAN','C'),
('Fulgur','POWER_PLANT','S3','MILITARY','B'),
('FullBlock','SHIELD','S3','MILITARY','B'),
('FullForce','POWER_PLANT','S2','CIVILIAN','C'),
('FullForce Pro','POWER_PLANT','S3','CIVILIAN','C'),
('FullFrost','COOLER','S2','CIVILIAN','B'),
('FullStop','SHIELD','S2','MILITARY','C'),
('Galinstan','COOLER','S3','MILITARY','D'),
('GammaMax','POWER_PLANT','S2','STEALTH','B'),
('Gelid','COOLER','S1','CIVILIAN','A'),
('Genoa','POWER_PLANT','S2','INDUSTRIAL','A'),
('Ginzel','POWER_PLANT','S3','INDUSTRIAL','C'),
('Glacier','COOLER','S1','MILITARY','A'),
('Goliath','QUANTUM_DRIVE','S1','INDUSTRIAL','C'),
('Graupel','COOLER','S2','CIVILIAN','C'),
('GUARD','SHIELD','S3','CIVILIAN','C'),
('Guardian','SHIELD','S1','INDUSTRIAL','B'),
('Haltur','SHIELD','S2','COMPETITION','B'),
('HAVEN','SHIELD','S3','CIVILIAN','D'),
('HeatSafe','COOLER','S1','STEALTH','C'),
('HeatSink','COOLER','S2','STEALTH','C'),
('Hemera','QUANTUM_DRIVE','S2','CIVILIAN','A'),
('HEX','SHIELD','S1','CIVILIAN','B'),
('Huracan','QUANTUM_DRIVE','S2','INDUSTRIAL','B'),
('Hydrocel','COOLER','S1','INDUSTRIAL','D'),
('HydroJet','COOLER','S2','INDUSTRIAL','D'),
('Hydropulse','COOLER','S3','INDUSTRIAL','D'),
('HyperGen','POWER_PLANT','S1','MILITARY','D'),
('Hyperion','QUANTUM_DRIVE','S1','CIVILIAN','B'),
('Ice-Flush','COOLER','S3','INDUSTRIAL','B'),
('IceBox','COOLER','S2','STEALTH','B'),
('IceDive','COOLER','S2','COMPETITION','C'),
('IcePlunge','COOLER','S1','COMPETITION','C'),
('Impulse','QUANTUM_DRIVE','S3','CIVILIAN','B'),
('INK','SHIELD','S1','CIVILIAN','D'),
('IonBurst','POWER_PLANT','S1','CIVILIAN','B'),
('IonSurge','POWER_PLANT','S2','CIVILIAN','B'),
('IonSurge Pro','POWER_PLANT','S3','CIVILIAN','B'),
('IonWave','POWER_PLANT','S0','CIVILIAN','B'),
('Jaghte','SHIELD','S1','COMPETITION','B'),
('Jennet','POWER_PLANT','S0','INDUSTRIAL','D'),
('JS-300','POWER_PLANT','S1','MILITARY','A'),
('JS-400','POWER_PLANT','S2','MILITARY','A'),
('JS-500','POWER_PLANT','S3','MILITARY','A'),
('Kama','QUANTUM_DRIVE','S3','INDUSTRIAL','C'),
('Kelvid','COOLER','S0','CIVILIAN','B'),
('Khaos','QUANTUM_DRIVE','S2','CIVILIAN','C'),
('Kragen','COOLER','S3','CIVILIAN','A'),
('LightBlossom','POWER_PLANT','S1','CIVILIAN','C'),
('LightFire','QUANTUM_DRIVE','S1','COMPETITION','C'),
('Lotus','POWER_PLANT','S2','CIVILIAN','A'),
('LumaCore','POWER_PLANT','S1','COMPETITION','A'),
('LuxCore','POWER_PLANT','S2','COMPETITION','A'),
('Maelstrom','POWER_PLANT','S2','MILITARY','C'),
('MagnaBloom','POWER_PLANT','S1','CIVILIAN','B'),
('MegaFlux','POWER_PLANT','S3','MILITARY','B'),
('Mercury','COOLER','S3','MILITARY','C'),
('Metis','QUANTUM_DRIVE','S3','CIVILIAN','C'),
('Mirage','SHIELD','S1','STEALTH','A'),
('NewDawn','POWER_PLANT','S3','CIVILIAN','C'),
('NightFall','COOLER','S2','STEALTH','A'),
('Nova','QUANTUM_DRIVE','S2','STEALTH','C'),
('Obscura','SHIELD','S2','STEALTH','C'),
('Odyssey','QUANTUM_DRIVE','S2','CIVILIAN','C'),
('OverDrive','POWER_PLANT','S1','MILITARY','C'),
('Palisade','SHIELD','S1','INDUSTRIAL','A'),
('Parapet','SHIELD','S3','INDUSTRIAL','A'),
('Permafrost','COOLER','S2','MILITARY','B'),
('PIN','SHIELD','S0','CIVILIAN','C'),
('Polar','COOLER','S1','MILITARY','B'),
('Pontes','QUANTUM_DRIVE','S3','MILITARY','C'),
('PowerBolt','POWER_PLANT','S1','CIVILIAN','C'),
('QuadraCell','POWER_PLANT','S1','MILITARY','A'),
('QuadraCell MT','POWER_PLANT','S2','MILITARY','A'),
('QuadraCell MX','POWER_PLANT','S3','MILITARY','A'),
('Quest','QUANTUM_DRIVE','S2','CIVILIAN','D'),
('QuikCool','COOLER','S1','COMPETITION','D'),
('Radiance','POWER_PLANT','S2','CIVILIAN','B'),
('Radix','POWER_PLANT','S0','CIVILIAN','C'),
('Rampart','SHIELD','S2','INDUSTRIAL','A'),
('Ranger','QUANTUM_DRIVE','S3','CIVILIAN','B'),
('RapidCool','COOLER','S2','COMPETITION','D'),
('Regulus','POWER_PLANT','S1','MILITARY','C'),
('Reliance','POWER_PLANT','S3','INDUSTRIAL','B'),
('Roughneck','POWER_PLANT','S1','INDUSTRIAL','D'),
('RPEL','SHIELD','S2','CIVILIAN','D'),
('Rush','QUANTUM_DRIVE','S1','CIVILIAN','C'),
('SecureHyde','SHIELD','S1','MILITARY','D'),
('SecureScreen','SHIELD','S3','MILITARY','D'),
('SecureSHIELD','SHIELD','S2','MILITARY','D'),
('Sedulity','POWER_PLANT','S2','INDUSTRIAL','B'),
('Sheut','SHIELD','S2','STEALTH','B'),
('Shimmer','SHIELD','S1','STEALTH','C'),
('Shroud','SHIELD','S2','STEALTH','D'),
('Siren','QUANTUM_DRIVE','S1','MILITARY','B'),
('Slipstream','POWER_PLANT','S1','STEALTH','A'),
('SmartGen','POWER_PLANT','S3','MILITARY','D'),
('SnowBlind','COOLER','S1','STEALTH','A'),
('Snowfall','COOLER','S2','INDUSTRIAL','B'),
('Snowpack','COOLER','S2','INDUSTRIAL','A'),
('Sojourn','QUANTUM_DRIVE','S2','CIVILIAN','B'),
('SolarFlare','POWER_PLANT','S2','COMPETITION','C'),
('SonicLite','POWER_PLANT','S1','STEALTH','C'),
('SparkFire','QUANTUM_DRIVE','S2','COMPETITION','C'),
('SparkJet','POWER_PLANT','S2','CIVILIAN','D'),
('SparkJet Pro','POWER_PLANT','S3','CIVILIAN','D'),
('Spectre','QUANTUM_DRIVE','S1','STEALTH','A'),
('Spicule','QUANTUM_DRIVE','S2','STEALTH','A'),
('StarBurn','POWER_PLANT','S2','COMPETITION','B'),
('StarHeart','POWER_PLANT','S1','COMPETITION','B'),
('Steadfast','POWER_PLANT','S0','INDUSTRIAL','C'),
('Steward','SHIELD','S1','INDUSTRIAL','D'),
('STOP','SHIELD','S2','CIVILIAN','C'),
('Stronghold','SHIELD','S3','INDUSTRIAL','C'),
('Sukoran','SHIELD','S2','MILITARY','C'),
('Suldrath','SHIELD','S1','MILITARY','C'),
('SunFire','QUANTUM_DRIVE','S2','COMPETITION','B'),
('SunFlare','POWER_PLANT','S1','COMPETITION','C'),
('SuperDrive','POWER_PLANT','S3','MILITARY','C'),
('SureStop','SHIELD','S3','MILITARY','C'),
('Taiga','COOLER','S2','CIVILIAN','B'),
('Targa','SHIELD','S1','COMPETITION','C'),
('Tempest','COOLER','S3','MILITARY','B'),
('Tepilo','COOLER','S0','CIVILIAN','A'),
('ThermalCore','COOLER','S3','INDUSTRIAL','C'),
('Thermax','COOLER','S1','INDUSTRIAL','C'),
('TigerLilly','POWER_PLANT','S3','CIVILIAN','A'),
('Torrent','QUANTUM_DRIVE','S2','CIVILIAN','C'),
('Trenta','SHIELD','S2','COMPETITION','C'),
('Trommel','POWER_PLANT','S2','INDUSTRIAL','D'),
('TS-2','QUANTUM_DRIVE','S3','MILITARY','A'),
('Tundra','COOLER','S1','MILITARY','D'),
('TurboDrive','POWER_PLANT','S2','MILITARY','C'),
('Tyche','QUANTUM_DRIVE','S3','CIVILIAN','B'),
('Ultra-Flow','COOLER','S1','INDUSTRIAL','A'),
('UltraFlux','POWER_PLANT','S2','MILITARY','B'),
('Umbra','SHIELD','S2','STEALTH','A'),
('VaporBlock','COOLER','S1','STEALTH','B'),
('Veil','SHIELD','S1','STEALTH','B'),
('Vesta','QUANTUM_DRIVE','S3','INDUSTRIAL','D'),
('VK-00','QUANTUM_DRIVE','S1','MILITARY','A'),
('Vortex','POWER_PLANT','S2','MILITARY','D'),
('Voyage','QUANTUM_DRIVE','S1','CIVILIAN','B'),
('Vulcan','QUANTUM_DRIVE','S1','INDUSTRIAL','D'),
('Wanderer','QUANTUM_DRIVE','S3','CIVILIAN','C'),
('Ward','SHIELD','S3','INDUSTRIAL','D'),
('Wayfare','QUANTUM_DRIVE','S1','CIVILIAN','D'),
('WEB','SHIELD','S1','CIVILIAN','C'),
('WhiteOut','COOLER','S2','CIVILIAN','D'),
('WhiteRose','POWER_PLANT','S1','CIVILIAN','A'),
('Winter-Star','COOLER','S1','CIVILIAN','D'),
('Winter-Star EX','COOLER','S2','CIVILIAN','D'),
('Winter-Star SL','COOLER','S0','CIVILIAN','D'),
('Winter-Star XL','COOLER','S3','CIVILIAN','D'),
('XL-1','QUANTUM_DRIVE','S2','MILITARY','A'),
('Yaluk','QUANTUM_DRIVE','S2','INDUSTRIAL','D'),
('Yeager','QUANTUM_DRIVE','S2','MILITARY','B'),
('ZapJet','POWER_PLANT','S1','CIVILIAN','D'),
('Zephyr','QUANTUM_DRIVE','S1','STEALTH','B'),
('ZeroRush','COOLER','S1','COMPETITION','B') ON CONFLICT DO NOTHING;

-- migrate:down
