services:
  client:
    build:
      args:
        FONTAWESOME_NPM_TOKEN: ${FONTAWESOME_NPM_TOKEN}
      context: ./packages/client
    container_name: explorator-client
    depends_on:
      - server
    # depends_on:
    #   database:
    #     condition: service_healthy
    environment:
      PORT_CLIENT: ${PORT_CLIENT}
    extra_hosts:
        - "host.docker.internal:host-gateway"
    ports:
      - ${PORT_CLIENT}:${PORT_CLIENT}
    restart: unless-stopped

  database:
    build:
      context: ./db
    command: ["-c", "log_statement=all", "-p", "${PORT_DATABASE}"]
    container_name: explorator-database
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-h",
          "${DOCKER_DOMAIN}",
          "-p",
          "${PORT_DATABASE}",
          "-U",
          "${DATABASE_USER}",
        ]
      interval: 10s
      timeout: 5s
      retries: 4
    # image: postgres:17.5-alpine
    ports:
      - ${PORT_DATABASE}:${PORT_DATABASE}
    restart: unless-stopped
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d

  migrations:
    command: ["--wait", "up"]
    container_name: explorator-migrations
    depends_on:
      - database
    environment:
      DATABASE_URL: ${DOCKER_DATABASE_URL}
    image: ghcr.io/amacneil/dbmate
    volumes:
      - ./db:/db

  server:
    build:
      context: ./packages/server
    container_name: explorator-server
    depends_on:
      database:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DOCKER_DATABASE_URL}
      PORT_SERVER: ${PORT_SERVER}
    ports:
      - ${PORT_SERVER}:${PORT_SERVER}
    restart: unless-stopped
